version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: chat-service-db
    environment:
      POSTGRES_DB: chat_service
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chat_user -d chat_service -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: chat-service:prod
    command: ["node", "api/index.js"]
    
    environment:
      NODE_ENV: production
      PORT: 3000
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: chat_user
      PGPASSWORD: chat_password
      PGDATABASE: chat_service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 10s
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/',res=>process.exit(res.statusCode===200?0:1))"]

volumes:
  postgres_data:
