name: CI/CD chat-service

on:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run tests (with coverage)
        run: npm test -- --coverage
        env:
          NODE_ENV: test

      - name: Security audit (non-blocking)
        run: npm audit --production || true

  deploy:
    name: Deploy to Vercel (Production)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    # ⬇️ Si ton projet est dans un sous-dossier (ex: ./chat-service),
    # ajoute "working-directory: ./chat-service" sur les 3 étapes vercel.
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Vercel Pull (project & env)
        run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_DEPLOY }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Vercel Build (prebuild)
        run: npx vercel build --prod --token=${{ secrets.VERCEL_DEPLOY }}

      - name: Vercel Deploy (use prebuilt)
        run: npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_DEPLOY }}
